# Generated by Django 5.0.7 on 2024-07-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postalrecord',
            name='city',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='postalrecord',
            name='country',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='postalrecord',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postalrecord',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
